-
  name: Play1
  hosts: target1
  
  tasks:
    - name: Run Docker-Compose
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ lookup('file', '/home/ec2-user/keypair') }}"
      script: script.sh
